kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:

  - name: test
    image: openjdk:20-slim
    commands:
      - apt-get update
      - apt-get install git
      - ./gradlew applyPatches
      - ./gradlew test